# Generated by Django 4.1.13 on 2023-11-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('TA', 'Teaching Assistant'), ('Student', 'Student')], default='Student', max_length=100),
        ),
    ]
