# Generated by Django 4.1.13 on 2023-11-27 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0003_queueentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='in_queue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
