# Generated by Django 4.1.13 on 2023-12-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0005_queueentry_assisting_ta'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='class_field',
            field=models.CharField(default='CSE 330', max_length=100),
        ),
    ]
